import type { SocialEvent } from '../types/index.js';
import { initializeEvents } from '../services/eventService.js';

// Initial events data matching the frontend's socialEvents.ts
// This should be called on server startup to seed the events
export const initialEvents: SocialEvent[] = [
  {
    id: 1,
    title: 'Wednesday Playtime',
    date: '2026-01-14',
    time: '7:00 PM - 10:00 PM',
    dayOfWeek: 'Wednesday',
    location: 'Altona SportsPoint Badminton Club',
    description:
      'Weekly Wednesday social play session. All skill levels welcome! Perfect way to start your week with some badminton action.',
    maxCapacity: 45,
    currentAttendees: 15,
    price: 20,
    imageUrl: '/assets/DemonSlayerW.png',
    status: 'available',
    category: 'regular',
    recurring: true,
  },
  {
    id: 2,
    title: 'Friday Playtime',
    date: '2026-04-24',
    time: '7:00 PM - 10:00 PM',
    dayOfWeek: 'Friday',
    location: 'Stomers Badminton Club',
    description:
      'Weekly Friday social play session. Fun games and friendly matches! Perfect way to end your week with some badminton action.',
    maxCapacity: 45,
    currentAttendees: 45,
    price: 20,
    imageUrl: '/assets/MapleStoryF.png',
    status: 'full',
    category: 'regular',
    recurring: true,
  },
  {
    id: 3,
    title: 'Friday Playtime',
    date: '2026-01-30',
    time: '7:00 PM - 10:00 PM',
    dayOfWeek: 'Friday',
    location: 'Altona Meadows Badminton Club',
    description:
      'Weekly Friday social play session. Fun games and friendly matches! Perfect way to end your week with some badminton action.',
    maxCapacity: 20,
    currentAttendees: 8,
    price: 20,
    imageUrl: '/assets/DemonSlayerW.png',
    status: 'available',
    category: 'regular',
    recurring: true,
  },
  {
    id: 4,
    title: 'Friday Playtime',
    date: '2026-02-06',
    time: '7:00 PM - 10:00 PM',
    dayOfWeek: 'Friday',
    location: 'Stomers Badminton Club',
    description:
      'Weekly Friday social play session. Fun games and friendly matches! Perfect way to end your week with some badminton action.',
    maxCapacity: 45,
    currentAttendees: 45,
    price: 20,
    imageUrl: '/assets/MapleStoryF.png',
    status: 'available',
    category: 'regular',
    recurring: true,
  },
  {
    id: 5,
    title: 'Chibi battle royale #4',
    date: '2026-12-21',
    time: '6:00 PM - 11:00 PM',
    dayOfWeek: 'Saturday',
    location: 'Krisna Badminton Club',
    description:
      'Join us for a special tournament night! Competitive matches with prizes for winners. All skill levels welcome to participate or watch.',
    maxCapacity: 70,
    currentAttendees: 30,
    price: 70,
    imageUrl: '/assets/BattleMain.png',
    status: 'available',
    category: 'tournament',
    recurring: true,
  },
  {
    id: 6,
    title: 'Friday Playtime',
    date: '2026-01-23',
    time: '6:00 PM - 9:00 PM',
    dayOfWeek: 'Friday',
    location: 'Stomers Badminton Club',
    description:
      'Weekly Friday social play session. Fun games and friendly matches! Perfect way to end your week with some badminton action.',
    maxCapacity: 45,
    currentAttendees: 20,
    price: 20,
    imageUrl: '/assets/BattleMain.png',
    status: 'available',
    category: 'regular',
    recurring: false,
  },
  // Completed events (past events)
  {
    id: 7,
    title: 'Wednesday Playtime',
    date: '2026-01-07',
    time: '7:00 PM - 10:00 PM',
    dayOfWeek: 'Wednesday',
    location: 'Altona SportsPoint Badminton Club',
    description:
      'Weekly Wednesday social play session. All skill levels welcome! Perfect way to start your week with some badminton action.',
    maxCapacity: 45,
    currentAttendees: 45,
    price: 20,
    imageUrl: '/assets/DemonSlayerW.png',
    status: 'completed',
    category: 'regular',
    recurring: true,
  },
  {
    id: 8,
    title: 'Friday Playtime',
    date: '2026-01-09',
    time: '7:00 PM - 10:00 PM',
    dayOfWeek: 'Friday',
    location: 'Stomers Badminton Club',
    description:
      'Weekly Friday social play session. Fun games and friendly matches! Perfect way to end your week with some badminton action.',
    maxCapacity: 45,
    currentAttendees: 45,
    price: 20,
    imageUrl: '/assets/MapleStoryF.png',
    status: 'completed',
    category: 'regular',
    recurring: true,
  },
  {
    id: 9,
    title: 'Wednesday Playtime',
    date: '2025-12-31',
    time: '9:00 AM - 5:00 PM',
    dayOfWeek: 'Wednesday',
    location: 'Altona SportsPoint Badminton Club',
    description:
      'Weekly Wednesday social play session. All skill levels welcome! Perfect way to start your week with some badminton action.',
    maxCapacity: 45,
    currentAttendees: 45,
    price: 20,
    imageUrl: '/assets/DemonSlayerW.png',
    status: 'completed',
    category: 'regular',
    recurring: true,
  },
  {
    id: 10,
    title: 'Friday Playtime',
    date: '2026-01-16',
    time: '7:00 PM - 10:00 PM',
    dayOfWeek: 'Friday',
    location: 'Stomers Badminton Club',
    description:
      'Weekly Friday social play session. Fun games and friendly matches! Perfect way to end your week with some badminton action.',
    maxCapacity: 45,
    currentAttendees: 35,
    price: 20,
    imageUrl: '/assets/MapleStoryF.png',
    status: 'available',
    category: 'regular',
    recurring: true,
  },
  {
    id: 11,
    title: 'Wednesday Playtime',
    date: '2026-01-23',
    time: '7:00 PM - 10:00 PM',
    dayOfWeek: 'Wednesday',
    location: 'Altona Meadows Badminton Club',
    description:
      'Weekly Wednesday social play session. All skill levels welcome! Perfect way to start your week with some badminton action.',
    maxCapacity: 45,
    currentAttendees: 25,
    price: 20,
    imageUrl: '/assets/DemonSlayerW.png',
    status: 'available',
    category: 'regular',
    recurring: true,
  },
  {
    id: 12,
    title: 'Wednesday Playtime',
    date: '2026-01-30',
    time: '7:00 PM - 10:00 PM',
    dayOfWeek: 'Wednesday',
    location: 'Altona Meadows Badminton Club',
    description:
      'Weekly Wednesday social play session. All skill levels welcome! Perfect way to start your week with some badminton action.',
    maxCapacity: 45,
    currentAttendees: 25,
    price: 20,
    imageUrl: '/assets/DemonSlayerW.png',
    status: 'available',
    category: 'regular',
    recurring: true,
  },
  {
    id: 13,
    title: 'Wednesday Playtime',
    date: '2026-02-06',
    time: '7:00 PM - 10:00 PM',
    dayOfWeek: 'Wednesday',
    location: 'Altona Meadows Badminton Club',
    description:
      'Weekly Wednesday social play session. All skill levels welcome! Perfect way to start your week with some badminton action.',
    maxCapacity: 45,
    currentAttendees: 25,
    price: 20,
    imageUrl: '/assets/DemonSlayerW.png',
    status: 'available',
    category: 'regular',
    recurring: true,
  },
  {
    id: 14,
    title: 'Wednesday Playtime',
    date: '2026-02-13',
    time: '7:00 PM - 10:00 PM',
    dayOfWeek: 'Wednesday',
    location: 'Altona SportsPoint Badminton Club',
    description:
      'Weekly Wednesday social play session. All skill levels welcome! Perfect way to start your week with some badminton action.',
    maxCapacity: 45,
    currentAttendees: 45,
    price: 20,
    imageUrl: '/assets/DemonSlayerW.png',
    status: 'full',
    category: 'regular',
    recurring: true,
  },
  {
    id: 15,
    title: 'Chibi battle royale #3',
    date: '2025-12-21',
    time: '6:00 PM - 11:00 PM',
    dayOfWeek: 'Saturday',
    location: 'Krisna Badminton Club',
    description:
      'Join us for a special tournament night! Competitive matches with prizes for winners. All skill levels welcome to participate or watch.',
    maxCapacity: 70,
    currentAttendees: 70,
    price: 50,
    imageUrl: '/assets/BattleMain.png',
    status: 'completed',
    category: 'tournament',
    recurring: true,
  },
  {
    id: 16,
    title: 'Chibi battle royale #2',
    date: '2024-12-21',
    time: '6:00 PM - 11:00 PM',
    dayOfWeek: 'Saturday',
    location: 'Krisna Badminton Club',
    description:
      'Join us for a special tournament night! Competitive matches with prizes for winners. All skill levels welcome to participate or watch.',
    maxCapacity: 70,
    currentAttendees: 70,
    price: 50,
    imageUrl: '/assets/BattleMain.png',
    status: 'completed',
    category: 'tournament',
    recurring: true,
  },
  {
    id: 17,
    title: 'Chibi battle royale #1',
    date: '2023-12-21',
    time: '6:00 PM - 11:00 PM',
    dayOfWeek: 'Saturday',
    location: 'Krisna Badminton Club',
    description:
      'Join us for a special tournament night! Competitive matches with prizes for winners. All skill levels welcome to participate or watch.',
    maxCapacity: 70,
    currentAttendees: 70,
    price: 50,
    imageUrl: '/assets/BattleMain.png',
    status: 'completed',
    category: 'tournament',
    recurring: true,
  },
];

// Initialize events on import
initializeEvents(initialEvents);
